### ISSUE TITLE
request: support putting coqprime in COQPATH

### ISSUE THREAD

**Issue by andres-erbsen** [thery/coqprime#1]
Hi,

[`fiat-crypto`](https://github.com/mit-plv/fiat-crypto) depends on coqprime for number theory lemmas (and potentially for actual primality proofs in the future). Currently, we bundle an out-of-date version of coqprime at <https://github.com/mit-plv/fiat-crypto/tree/master/coqprime>, which mostly works for us. However, this arrangement is causing the Coq developers a fair amount of headache, e.g. <https://github.com/mit-plv/fiat-crypto/pull/269> and <https://github.com/mit-plv/fiat-crypto/pull/316>. We would like to change `fiat-crypto` to include coqprime as a git submodule in the `fiat-crypto` `COQPATH`. We already do this for [bbv](https://github.com/mit-plv/bbv) (https://github.com/mit-plv/fiat-crypto/commit/e11d6d06e6eda3cd5940765dbbea420416725832), and [cross-crypto](https://github.com/mit-plv/cross-crypto) does this for [fcf](https://github.com/adampetcher/fcf).

This would require rearranging the coqprime directory structure such that `List` would become `src/Coqprime/List`, where `src` is just any directory that only contains Coq files and `Coqprime` determines the form of `Require Import Coqprime.PrimalityTest`. This would probably require changes in `Make` and etc. Would a change like this be acceptable to coqprime? I am willing to volunteer to work on this, though I am not sure I understand the coqprime build situation well enough to be certain that I don't break anything, so I probably wouldn't get everything right on the first try.

Thanks,
Andres

**Comment by thery** [comment]
Ok I've created your hierarchy. Tell me if it is ok

**Comment by JasonGross** [comment]
Seems closed by #3 ?

**Comment by andres-erbsen** [comment]
Yep; Thanks!
