### ISSUE TITLE
Please create a tag for Coq 8.14 in Coq Platform 2021.11

### ISSUE THREAD

**Issue by MSoegtropIMC** [thery/coqprime#29]
The Coq team released Coq 8.14+rc1 on September 17, 2021 and plans to release Coq 8.14.0 before October 31, 2021.
The corresponding Coq Platform release 2021.11 should be released before November 30, 2021.
It can be delayed in case of difficulties until January 31, 2022, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knoweldege the latest released version of your project (1.0.6) does not work with Coq 8.14+rc1.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI is currently testing commit d4bcfa8f7d7bdbe879d842ecfe575406f622c8ae on repository https://github.com/thery/coqprime - which likely means that this commit does work in Coq CI.

Could you please create a tag, or communicate us any existing tag that works with Coq branch v8.14, preferably before November 15, 2021?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

The working branch of Coq Platform, which already supports Coq version 8.14+rc1, can be found here https://github.com/coq/platform/tree/main.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/139

**Comment by thery** [comment]
@MSoegtropIMC sorry coq is becoming too technological for me.  I've lost my morning trying to compile coq8.14 and now I am stuck trying to compile bignums. Is there an easy to get a hold on coq8.14+rc1?

**Comment by thery** [comment]
@MSoegtropIMC  I finally got something that seems to work (coq + bignums) and coqprime compiles for it. I wonder if the last commit by @SkySkimmer fixes the problem. Can you retry seeing if there is a problem with the current version of master.

**Comment by MSoegtropIMC** [comment]
@thery : yes, I will try that.

Btw.: you might want to try the Coq Platform scripts linked above to reproduce the state I am testing. This branch includes Coq 8.14+rc1 (and a few other versions). The scripts should be easy to use. If you already have opam, they will create a new opam switch, so that nothing of your current opam state is touched, otherwise they will setup opam. Just download the zip from the above branch and run the coq_platform_make.sh script (for macOS, Linux or the .bat file on Windows). It will ask a few questions and then install opam, Coq, ....

**Comment by thery** [comment]
@MSoegtropIMC I have tried no problem with coq.8.14rc1 but I also need coq-bignums and it does not seem available.

**Comment by MSoegtropIMC** [comment]
The Coq Platform development (main) branch tends to have a largish number of local opam patches. coq-bignums is included there.

See (https://github.com/coq/platform/tree/main/opam/opam-coq-archive/extra-dev/packages)
specifically (https://github.com/coq/platform/blob/main/opam/opam-coq-archive/extra-dev/packages/coq-bignums/coq-bignums.8.14.0/opam)

The reason I do it this way is that I need to change some opam packages a few times to adjust them to requirements of additional packages and it is less messy to publish the final result - I will do the PRs tomorrow.

**Comment by thery** [comment]
@MSoegtropIMC with coq 8.14 of the platform + local installation of bignum, the current version of Coqprime compiles. There are many warning about rewrite hint that I will try to fix soon.

**Comment by MSoegtropIMC** [comment]
@thery : thanks, I will check what went wrong in my tests - maybe just a typo in a test script or the like.

**Comment by MSoegtropIMC** [comment]
Hmm, when I try in the 8.14+rc1 version of Coq Platform (that is in `opam switch __coq-platform.2021.09.0~8.14+beta1`) the command:
```
opam install coq-coqprime.1.0.6
```
It fails with an error (only visible in the opam log file - the log tail has warnings):
```
File "./src/Coqprime/Z/ZCAux.v", line 188, characters 0-9:
Error: No product even after head-reduction.
```

Did you try installation via opam or did you compile it locally? Maybe something is wrong with the opam file (it works with 8.13, though).

**Comment by thery** [comment]
sorry I've compiled it against master, my bad. 
I've just added a tag v8.14.

Sorry again to wasting your time,

**Comment by MSoegtropIMC** [comment]
No issue - Coq Platform makes such tests quick.

So are you saying coq-prime 1.0.6 (which uses tag v8.12) works with Coq 8.13.2 and Coq master but not with 8.14+rc1?
Or did you mean you compiled coq-prime master against 8.14+rc1?

I don't see the tag on this git repo yet - did you push it?

**Comment by thery** [comment]
no I'ven´t retrieved 1.0.6  I was compiling coqprime/master with 8.14rc1

The tag is pushed now. Should I have to do a  release 1.1?

**Comment by MSoegtropIMC** [comment]
> no I'ven´t retrieved 1.0.6 I was compiling coqprime/master with 8.14rc1

Ah ok, this explains it.

> The tag is pushed now. Should I have to do a release 1.1?

You mean on opam? yes please!

**Comment by thery** [comment]
done [#1849](https://github.com/coq/opam-coq-archive/pull/1849#)

**Comment by MSoegtropIMC** [comment]
@thery : I updated Coq Platform 2021.09. Thanks!

**Comment by MSoegtropIMC** [comment]
@thery : I made a straight forward autoconf file and it finds the libraries gmp and gmp-ecm.

But there is one issue: you use `__ecm_get_random_ul` (unsigned long) but the version of ecm available on macports (6.3) doesn't have this function, only `__ecm_get_random_ui` (for int instead of long).

I guess you need gmp-ecm 7.X - which means I would have to update gmp-ecm on MacPorts.

**Comment by MSoegtropIMC** [comment]
@thery : I simply created an opam package for library gmp-ecm. This works. I guess for such rather exotic libraries this is the safest way to get a reproducible version in a platform independent way.

**Comment by MSoegtropIMC** [comment]
@thery : the certificate generator is now also included in Coq Platform (well still in my local working branch, but soon).

**Comment by thery** [comment]
@MSoegtropIMC  Thanks!
