### ISSUE TITLE
Syntax issue in examples

### ISSUE THREAD

**Issue by MSoegtropIMC** [thery/coqprime#31]
Many of the examples contain `Open Local Scope`. I am not sure since when, but this does not compile any more. It should now be `Local Open Scope`.

**Comment by thery** [comment]
@MSoegtropIMC   I will have a look at it

**Comment by thery** [comment]
Thie brach [examples](https://github.com/thery/coqprime/tree/examples) should fix the problem. I will merge it when I have double checked

**Comment by MSoegtropIMC** [comment]
Thanks, looks good to me.

**Comment by MSoegtropIMC** [comment]
This appears to be fixed in master, so I will close this issue.
