### ISSUE TITLE
Please restore compatibility of opam package with Coq 8.12 and 8.13

### ISSUE THREAD

**Issue by JasonGross** [thery/coqprime#36]
`opam install coq-coqprime` on 8.13 [fails with](https://github.com/mit-plv/fiat-crypto/runs/4291028316?check_suite_focus=true#step:16:3810)
```
File "./src/Coqprime/Z/ZCmisc.v", line 31, characters 0-95:
Error: This command does not support this attribute: export.
[unsupported-attributes,parsing]
```
8.12 [has the same issue](https://github.com/mit-plv/fiat-crypto/runs/4291028436?check_suite_focus=true#step:16:3324)

**Comment by thery** [comment]
sorry, should be ok now

**Comment by JasonGross** [comment]
Great, thanks!  I've restarted the workflow runs, so hopefully they'll succeed now

**Comment by JasonGross** [comment]
The offending code still seems to be present on master, though?
https://github.com/thery/coqprime/blob/b95b7a0fe6bfe25389955334187d24715987ef51/src/Coqprime/Z/ZCmisc.v#L31-L33

**Comment by JasonGross** [comment]
And https://github.com/coq/opam-coq-archive/blob/master/extra-dev/packages/coq-coqprime/coq-coqprime.dev/opam claims that master is still compatible with Coq 8.12 (and I'd like it to stay this way, so that fiat-crypto dev can remain compatible with Coq 8.12)

**Comment by thery** [comment]
My bad. Time to go to bed. Should be ok now
