### ISSUE TITLE
[PATCH] firstprimes tool -- is 2 prime?

### ISSUE THREAD

**Issue by SnarkBoojum** [thery/coqprime#59]
In firstprime.c, the minimum can't be lower than 1, which means 2 is out of scope, since its index is 0.

The fix is as simple as:
```
--- coqprime.orig/gencertif/firstprimes.c
+++ coqprime/gencertif/firstprimes.c
@@ -11204,7 +11204,7 @@
     max = atoi(argv[2]);
   } else exit (1);
 
-  if (min < 1) min = 1;
+  if (min < 0) min = 0;
   if (max > MAXSIZE) max = MAXSIZE;
 
   out = fopen(filename,"w+");
```

**Comment by thery** [comment]
I had a quick look, it seems the certificate was invalid for min = 0. I've tried to fix that in the last commit.

Thanks!

**Comment by thery** [comment]
This is fixed
@SnarkBoojum I will close the issue
