### ISSUE TITLE
Manual pages for the tools

### ISSUE THREAD

**Issue by SnarkBoojum** [thery/coqprime#60]
While packaging for Debian, the packaging tools complained I was going to distribute binaries without manual pages, so I wrote some:
[firsprimes.txt](https://github.com/thery/coqprime/files/9119062/firsprimes.txt)
[o2v.txt](https://github.com/thery/coqprime/files/9119063/o2v.txt)
[pocklington.txt](https://github.com/thery/coqprime/files/9119064/pocklington.txt)
(those should be renamed from .txt to .1 -- github wants .txt)

**Comment by thery** [comment]
@SnarkBoojum I will close the issue
