### ISSUE TITLE
make -j is broken with Coq 8.7.2

### ISSUE THREAD

**Issue by JasonGross** [thery/coqprime#7]
6130c701eabc6a1a92afb6c7dd3f47653c050e34 broke compatibility with Coq 8.7.2.  Because this repo ships the makefile generated by Coq 8.8, which is not rebuilt if I'm using a different version of Coq, `coqdep` does not emit anything, and so there's no dependency ordering, and so `make` breaks if I pass it `-j`.

**Comment by thery** [comment]
Makefile is now unversioned and is generated by the ./configure.sh script
