### ISSUE TITLE
Gödel's beta-function

### ISSUE THREAD

**Issue by Casteran** [thery/coqprime#73]
@thery  In `N/ChineseRem.v` there are several definitions and theorems about the `beta`function, which are imported by the module `PRrepresentable` of Goedel project https://github.com/coq-community/hydra-battles/blob/master/theories/goedel/PRrepresentable.v .  
But this function is not explicitely named. Would it be possible to add to `N/ChineseRem.v` a definition of `beta` , for readability's sake ?

Please note that there are a few variants (number or order of arguments) in the litterature, but it's easy to convert from one variant to another.

**Comment by thery** [comment]
you want 
```
Definition beta (a z : nat) : nat :=
  snd
    (proj1_sig
       (div_eucl (coPrimeBeta z (cPairPi1 a)) (gtBeta z (cPairPi1 a))
          (cPairPi2 a))).
          ```
to be moved to Chinese rem? any support lemmas?

**Comment by Casteran** [comment]
Not exactly. 
  
  I just meant that the name beta could be defined in ChineseRem, for instance:

#[global] Notation rem a b Hposb :=
  (snd (proj1_sig (div_eucl b Hposb a))).

 Definition beta x y z := rem x (S (y * S z))  (gtBeta _ _).  (* Wikipedia’s definition *)

Lemma betaTheorem1 :
  forall (n : nat) (y : nat -> nat),
 {a : nat * nat |
   forall z: nat, z < n -> y z = beta (fst a) (snd a) z}.


  The beta function used in Goedel is easily related to the former one by the equality 
PRrepresentable.beta (cPair x y) z =  ChineseRem.beta y x z.
(Where cPair is (a variant of) the classical bijection from nat*nat into nat.

**Comment by thery** [comment]
Do a pull request I will merge it with pleasure. If you do it quick, it could be included in the new release for Coq 8.18

**Comment by Casteran** [comment]
I tried to write a PR. Can you access to it ?

**Comment by thery** [comment]
#76
